name: deploy my react app

on:
  push:
    branches: [main]

jobs:
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm i && npm run deploy